### ISSUE TITLE
FR: Anaphoric versions of `-table` and `-table-flat`

### ISSUE THREAD

**Issue by tmalsburg** [magnars/dash.el#139]
The readme file says that "there are also anaphoric versions of functions where that makes sense." I don't know if that is supposed to mean that anaphoric version of `-table` and `-table-flat` do not make sense or if they just haven't been implemented yet.  To me it seems they would be useful.

Thanks for dash.el, by the way, it's completely changing the way I write elisp code.

**Comment by Fuco1** [comment]
Only unary and binary functions have anaphoras. Since `-table` can take any number of lists and the function is of arbitrary arity, we do not provide an anaphoric version.

It could be conceived to produce one with `it1, it2, ... itn` but that's quickly adding on the "too much magic for my taste" scale.

Given that `-table` is not something you use every other line this isn't very important imo.

**Comment by tmalsburg** [comment]
You are of course absolutely right.  Hm, what was I thinking? Perhaps it was just too lat.  Thanks for the response.
