### ISSUE TITLE
Add dash.info to Info top level Index, after install

### ISSUE THREAD

**Issue by priyadarshan** [magnars/dash.el#189]
Hi,

I noticed dash.el has a very useful `dash.info`, which at the moment needs to be loaded manually.

It would be nice if it would be automatically included in the Info top index.

It is actually quite easy. To see how another package does that: https://github.com/webframp/sicp-info

I would do a PR, but lack necessary skills.

**Comment by Fuco1** [comment]
@holomorph any ideas about this?

**Comment by holomorph** [comment]
@Fuco1 Looking at `(info "(elisp) Multi-file Packages")`, it looks like this is sensible to do since dash already ships its info file.

**Comment by basil-conto** [comment]
> I noticed dash.el has a very useful `dash.info`

Not since #355, as it's autogenerated and package archives know how to do that :).

> which at the moment needs to be loaded manually.

Only if you install from GNU ELPA, but that's something I'm working on fixing in #344.

If you install from MELPA, the Texinfo manual is automatically installed as one would expect.

> it looks like this is sensible to do since dash already ships its info file.

No need; both GNU ELPA and MELPA can do that for us.

Since the only thing remaining to do here is update GNU ELPA, which is already tracked in #344, I'm closing this issue.
