### ISSUE TITLE
[Query] How to make dash's set operations etc available?

### ISSUE THREAD

**Issue by doolio** [magnars/dash.el#217]
`dash-2.13.0` was installed as a dependency of `magit-2.10.3` in my Emacs configuration and is therefore available on my `load-path`. Despite that I can't make use of set operations such as `-difference` provided by `dash.el`. When I explicitly load `dash.el` my use of `-difference` works as expected - great. But my understanding of the `README` is that once `dash.el` is on one's load path then all of its features are available. Is this not the case?

(Disclaimer: I'm an aspiring programmer, who jumped into the deep end in trying to learn Emacs from the beginning so please excuse my ignorance)

**Comment by Fuco1** [comment]
You're partially right.

When a library is in your `load-path` it just means you can `load` it: Emacs looks in all the directories on the `load-path` and loads the first matching file in the first directory where it is present.  But nothing is loaded automatically.

Usually packages provide a "feature" which is a symbol representing the library.  Then you `(require 'dash)` (dash is the `provide` from the `dash.el` library) and Emacs makes sure that it is only loaded once.  Therefore if 20 packages require dash it will only load once.  You should in general always require libraries and not load them.

There is also "autoloading" which works by adding stubs that when called actually load the library.  The autoloads are automatically generated if you install dash with `package.el` (`M-x package-list-packages`) which is the best way to add new packages to Emacs.  Then it will work by magic as you expect.

**Comment by doolio** [comment]
Forgive me for not being explicit. I installed `magit` from `melpa-stable` using `package.el` which downloaded `dash` as a dependency. And as you explained this generated the autoloads automatically and a `dash-autoloads.el` was created in my `~/.emacd.d/elpa/dash-2.13.0` directory. However, this file only seems to contain a line to add it to the `load-path` and an `;;;###autoload` cookie line. I notice though that `dash.el` does not contain any corresponding `;;;###autoload` cookie lines. So, I presume `update-file-autoloads` and/or `update-directory-autoloads` would not help here but one could add the autoload manually to their `init.el`?

But in any case, if I understood you correctly one still needs to load the generated files explicitly to make their autoloads available and as you advise it is best to `require` the library than `load` it.

I should add that I'm building my emacs configuration with `use-package` and although I have `require`d the feature `magit` with something like `(use-package magit)` there is no equivalent `(use-package dash)` declaration in my `init.el` at present. So I presume adding such a declaration would allow me to use the features of `dash.el` as I wish? Thanks for your time.

**Comment by Fuco1** [comment]
The autoload files generated by `package.el` are loaded automatically.  It seems that dash does not provide any autoloads :P (I thought it does, heh).  When the autoload is triggered it actually requires the requested file so it also only loads it once (the autoload stubs will all be replaced by the real functions at that moment as well).

When you first call any magit function it will automatically load dash as well because magit calls `(require 'dash)` somewhere in its code.

But yes, until you load `magit` dash will not load either.  If you want to have it available right away you will need to `require` it manually somewhere (or `(use-package dash)`).

It seems like it would be a good idea for dash to export its functions as autoloaded.  We might do that for the next version.

**Comment by doolio** [comment]
Thank you for taking the time to explain how all these things work. It has helped enormously with my understanding. Things are much clearer to me now so I guess we can consider this issue closed. As for whether `dash.el` should export its functions I can't say with my limited knowledge on all things Emacs but whilst trying to understand the problem I was having and this discussion I came across this great article by Sebastian Wiesner (aka lunaryorn) in which he argues libraries such as `dash.el` should not add any autoloads.

[http://www.lunaryorn.com/posts/autoloads-in-emacs-lisp.html](url)

Anyway, thanks again.

**Comment by Fuco1** [comment]
What he writes there makes sense but I don't see it as strictly, there is little harm in providing autoloads for "library" functions.  After all, Emacs does it as well internally (many `cl-` functions are autoloaded nowadays, see `M-x find-library cl-loaddefs`)

I for example use dash during the initialization of my Emacs so [I load it pretty early](https://github.com/Fuco1/.emacs.d/blob/master/init.el#L53); I actually `load` it because I'm using the dev checkout and so I give it the full path to avoid loading from elpa and I suppose most people do the same (= require early) because often you want it even before package.el is initialized.

So yea, either way works for me, it might actually add more confusion to new people like you if we made it autoloaded and other packages would seemingly not work then.

Cheers.
