### ISSUE TITLE
Let -min accept nil?

### ISSUE THREAD

**Issue by alphapapa** [magnars/dash.el#219]
I see that `-min` is defined so that it is identical to `min` itself.  It would be nice if it were defined something like this:
```el
(defun -min (&rest args)
  (setq args (cl-loop for arg in args
                      when arg
                      collect arg))
  (when args
    (apply 'min args)))
```
This allows doing something like:
```el
(-min 0 1 2 nil)
```
Compared to `min`, which gives an error due to the `nil`.  It would make it actually useful rather than merely a copy of `min`.  :)

For example, it comes in handy when checking several functions that give output as either a buffer position or `nil`, and choosing the smallest position from them.

Thanks.

**Comment by Fuco1** [comment]
`(-min (-non-nil list))` should work fine.  I prefer composition over complexity.

**Comment by alphapapa** [comment]
There is that, yes, but then what is the point of `-nil`?  :)

**Comment by Fuco1** [comment]
There is no `-nil`.

**Comment by alphapapa** [comment]
I meant `-min`.  I knew I was going to type the wrong one at some point.  :(

**Comment by Fuco1** [comment]
Right.  The rationale behind this was that we would like to have all the functions under the same namespace, so that sometimes we just alias the functions from Emacs into dash to have them discoverable.

**Comment by alphapapa** [comment]
I see, that makes sense.

Well, is there any chance of making an exception for `-min`?  Again, my reasoning is simply that it would make it a useful alternative to `min` in cases like I mentioned, where `min` gives an error, rather than merely being an alias for it.  It seems like it would fit into Dash's pattern (sometimes, at least) of, say, gently extending and correcting shortcomings in basic Emacs functions.

Thanks.

**Comment by Fuco1** [comment]
I was thinking about this and a logical return value in case of nil could also be nil itself instead of a number.  The least number case is also interesting though... I'm not sure if we should add a special case of `-min-ignore-nil` (with a better name) that would just filter the nils out first.  Or some version of `-min-by`.  I'm quite cautious in the presence of nils and undefines as that always leads to pain.  Which is why I still prefer an explicit filter/check before calling `-min`.

**Comment by alphapapa** [comment]
I guess `-min-non-nil` would combine the function names in a sensible way.

I think it makes sense to have a function like this, since there are functions in Emacs that return a buffer position or nil.  There should probably also be a `max` version.

> I'm quite cautious in the presence of nils and undefines as that always leads to pain. Which is why I still prefer an explicit filter/check before calling -min.

I agree, that does lead to pain.  That's why I made this suggestion in the first place, because of the pain `min` caused me.  ;)  I figured, if there's going to be a `-min`, it might as well be unique and "do the right thing" in such cases, to save the programmer from having to take the extra steps manually.

**Comment by Fuco1** [comment]
I'm going to close this as I still think `nil` should be handled explicitly, especially since it can mean many things in elisp (empty list, false...).  Making a special function for this would not save much over passing the input through `-not-nil` so is probably unnecessary.

If we silently ignore nils it can mask an error in the code and lead to unexpected results.
