### ISSUE TITLE
Deprecate variadic -list

### ISSUE THREAD

**Issue by alphapapa** [magnars/dash.el#225]
Maybe I'm missing something, but it seems that `-list` isn't working as advertised.

```
(-list &rest ARGS)

Return a list with ARGS.

If first item of ARGS is already a list, simply return ARGS.  
If not, return a list with ARGS as elements.
```
```el
(-list '(1) 2 3)  ; => (1)
```
It's not returning `ARGS`, it's returning `(car args)`, as seen in the function body:
```el
(defun -list (&rest args)
  (let ((arg (car args)))
    (if (listp arg) arg args)))
```
It seems like the function should be:
```el
(defun -list2 (&rest args)
  "Return a list with ARGS.

If first item of ARGS is already a list, simply return ARGS.  If
not, return a list with ARGS as elements."
  args)
```
So it would then work like the docstring says:
```el
(-list2 '(1) 2 3)  ; => ((1) 2 3)
(-list2 1 2 3)  ; => (1 2 3)
```
But I'm not sure I understand the purpose of checking the `car` of `args` anyway.  I'm sure you have your reasons, but I was hoping it would be something like this:
```el
(defun -list (&rest args)
  "Ensure ARG is a list."
  args)
```
Which is useful for functions that you want to accept an atom or a list.

Thanks.

P.S.  I don't mind the `-` prefix, but I have found one significant downside: it makes searching the issue list for issues about a certain function rather difficult, as the `-` seems to exclude matches.  I tried quoting the term but I still couldn't find anything related specifically to `-list`.

**Comment by basil-conto** [comment]
I believe the intended use of `-list` is to ensure its arguments always form a list. The discrepancy you see between the docstring and the implementation means the docstring is inaccurate. It should rather read

```elisp
(defun -list (&rest args)
  "Return a list with ARGS.

If the first element of ARGS is already a list, return it.
Otherwise, return a list with ARGS as elements.
  (let ((arg (car args)))
    (if (listp arg) arg args)))
```

This is used in only a [single place in `dash.el`](https://github.com/magnars/dash.el/blob/master/dash.el#L464):

```elisp
(defun -flatten-n (num list)
  "Flatten NUM levels of a nested LIST.
See also: `-flatten'"
  (declare (pure t) (side-effect-free t))
  (-last-item (--iterate (--mapcat (-list it) it) list (1+ num))))
```

Here it is used to "box" non-`nil` atoms in a list so that the results can be concatenated by `-mapcat`.

Personally, I think it is handy to have a function which boxes non-`nil` atoms in a list - it permits expressive/functional and yet relatively performant list filtering using `mapcan` and friends.

What I don't understand is why `-list` conflates this and the behaviour of the built-in `list` function. In other words, why does `-list` accept more than a single argument, when the built-in `list` can be used for that purpose instead. Does this generality benefit enough to mitigate the headache of a dual personality?

**Comment by Fuco1** [comment]
Yea @basil-conto hit the nail.  Frankly I don't know or remember why it takes multiple args, I think the intend was indeed to simply wrap atoms as lists so that you can pass whatever to functions expecting lists.

We should probably change the arglist to `(arg &rest args)` and add a note about deprecated calling convention with multiple arguments.

**Comment by alphapapa** [comment]
BTW, I recently noticed that `subr-x.el` has `internal--listify`:

```el
(defsubst internal--listify (elt)
  "Wrap ELT in a list if it is not one."
  (if (not (listp elt))
      (list elt)
    elt))
```

**Comment by basil-conto** [comment]
@alphapapa Note that, [as of recently](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=4612b2a2b37026bef5a9b8e92878a15dabb9b261), `internal--listify` no longer has the same role as `-list`.

**Comment by basil-conto** [comment]
> We should probably change the arglist to `(arg &rest args)` and add a note about deprecated calling convention with multiple arguments.

That would be a breaking change, so I've gone with the simpler fix in the docstring instead.

**Comment by Fuco1** [comment]
@basil-conto why would it be a breaking change?  If it is because we now require at least one argument, let's make it `&optional arg &rest args`.  I think it's a good idea to discourage the multi-arg usage as it makes no sense.

We should use `-list` to box and `list` to build.  Or maybe even create a new function `-as-list` but this then smells of e.g. converting vectors to lists etc.

**Comment by basil-conto** [comment]
> why would it be a breaking change? If it is because we now require at least one argument

Yes.

> let's make it `&optional arg &rest args`. I think it's a good idea to discourage the multi-arg usage as it makes no sense.

Fine by me, but since we're changing the function's preferred semantics, there's another important question as well: if the argument is already a list, do we return it as is, or do we return a copy?  As mentioned in #354, the problem with copying is that it's only possible for non-circular lists, and only efficient for proper lists.

**Comment by Fuco1** [comment]
Re circular/non-proper lists, I would not include them in dash's scope at all.  I barely ever came up to contact with them in the 10 years of Emacs use and probably never programmed with one.  It feels like a 99.99% outlier and not an interesting one either.

Good question about a copy... I think here I might prefer not a copy (due to a gut feeling :D), but that might be a bit confusing with regards to the overall assumptions about the package.  Hmm.

**Comment by basil-conto** [comment]
> Re circular/non-proper lists, I would not include them in dash's scope at all. I barely ever came up to contact with them in the 10 years of Emacs use and probably never programmed with one. It feels like a 99.99% outlier and not an interesting one either.

I'm afraid that ship has already sailed, because `-cycle` creates circular lists, as I mentioned in #354.

> Good question about a copy... I think here I might prefer not a copy (due to a gut feeling :D), but that might be a bit confusing with regards to the overall assumptions about the package. Hmm.

Since I'm not getting any clear indications about what to do about this, I'll need to think about it a bit more.  One possibility I'll consider is simply reverting the copies I added in #354 (since no-one seems to have complained about them until now), and documenting each function w.r.t. whether the result is a copy or an existing sub-structure.  At the end of the day, Elisp isn't built on fancy Clojure data structures with efficient copies, so a library can't be simultaneously 100% "pure" and efficient/practical.

**Comment by magnars** [comment]
Addressing this in documentation seems like the practical option here.
Otherwise we’d soon be implementing our own persistent data structures
instead.

fre. 8. jan. 2021 kl. 16:13 skrev Basil L. Contovounesios <
notifications@github.com>:
