### ISSUE TITLE
-compose is not available in version 2.18

### ISSUE THREAD

**Issue by bhrgunatha** [magnars/dash.el#372]
```
$ emacs --version 
GNU Emacs 27.1
```
The standard package installed from [Arch linux official repository](https://archlinux.org/packages/extra/x86_64/emacs/)
I have dash installed from melpa

package: dash-20210210.1449
The comment in dash.el says Version: 2.18.0

In the scratch buffer I evaluate these two lines
```lisp
(require 'dash)
(defun square (n) (* n n))
```
When I evaluate
```lisp
(message "%s" (-map (lambda (n) (square n)) '(1 2 3 4)))
```
I see `"(1 4 9 16)"` appear in the message area.
But when I try 

```lisp
(message "%s" (funcall (-compose 'square '+) 2 3))
```
I get `funcall: Symbol’s function definition is void: -compose`.

For some reason `-compose` is not recognised. This is preventing `lsp-mode` from working due to the latest version (lsp-mode 20210220.846) using `-compose`

Some issues have been reported and closed in the lsp-mode repo - [here's an example](https://github.com/emacs-lsp/lsp-mode/issues/2622) - which are fixed by updating outdated versions of dash to 2.18 (dash-20210210.1449) but for me it's not working. 

Any idea why `-compose` might be unavailable when `-map` **is**? 
Or what I can do to get emacs (in particular) `lsp-mode` to find it?

**Comment by basil-conto** [comment]
Sounds like your MELPA packages are in an inconsistent state, likely because of MELPA's using datetime package versions `YYYYMMDD` which are incompatible with canonical ELPA package versions such as `2.18.0`, because the former is always larger than the latter.

Does reinstalling `dash` and `dash-functional` solve the issue?  If so, and if none of your other packages depend on `dash-functional`, then it is also safe to delete `dash-functional` altogether, as the package is now deprecated, and all of its old definitions are provided by `dash`.

To avoid issues like these, I recommend installing `dash` from [GNU ELPA](https://elpa.gnu.org/packages/dash.html) rather than [MELPA](https://melpa.org/#/dash) (you may need to customise `package-pinned-packages` to achieve this depending on your setup).

**Comment by bhrgunatha** [comment]
Thanks, in fact now I've discovered that an older version of dash (2.17) installed elsewhere in which is getting picked up. So you're right my packages are in an inconsistent state. 
 
It's my mistake and I'm sorry to have bothered you - I'll close the issue.

**Comment by basil-conto** [comment]
It's no bother; thanks for confirming.
