### ISSUE TITLE
Combine multiple cdrs into one list for hooks simlification.

### ISSUE THREAD

**Issue by hongyi-zhao** [magnars/dash.el#387]
I currently install and configure python-mode with `use-package` as follows:
```emacs-lisp
(use-package python-mode
  :hook
  (python-mode . pyvenv-mode)
  (python-mode . try/pyvenv-workon)
  (python-mode . flycheck-mode)
  (python-mode . company-mode)
  (python-mode . yas-minor-mode))
```
I want to simplify the above multiple hook cons directives by
combination of the multiple cdrs into one list. Are there any tips for
achieving this goal with `dash` or similar tools? I've done some tries, as discussed [here](https://github.com/jwiegley/use-package/issues/954), but failed to do the trick.
 
Regards,
HZ

**Comment by basil-conto** [comment]
> Are there any tips for achieving this goal with `dash` or similar tools?

I don't see how Dash is relevant.  `use-package` is a macro and you want it to be evaluated.  You can always wrap it in ```(eval `(use-package ...) lexical-binding)```, and transform the contained forms to your liking, but that's not a very clean approach.

IMO `use-package` should be adapted to support your use-case, since it already tries to DWIM.

The next best thing, IMO, is to write your own `use-package` keyword (see `use-package-keywords`) that does what you want.  I don't use `use-package` anymore, but IIRC this was a supported use-case.

Finally, you could write your own macro that wraps `use-package`, but I don't see how that would be any better than creating your own keyword or the status quo.

If you really want to convert a flat list of symbols into an alist, it's pretty simple to do in Elisp even without Dash, e.g.:

```el
`(use-package python-mode
   :hook
   ,@(mapcar (lambda (fun) (cons 'python-mode fun))
             '( pyvenv-mode
                try/pyvenv-workon
                flycheck-mode
                company-mode
                yas-minor-mode )))
```

which evalutes to:

```el
(use-package python-mode
  :hook
  (python-mode . pyvenv-mode)
  (python-mode . try/pyvenv-workon)
  (python-mode . flycheck-mode)
  (python-mode . company-mode)
  (python-mode . yas-minor-mode))
```

The only "benefit" you would gain from Dash is writing `--map`, `-cut`, or some zip operation instead of `mapcar`, `lambda`, and `cons`.  Personally I wouldn't consider those any clearer in such a simple scenario.

HTH.

**Comment by yyoncho** [comment]
```
(use-package python-mode
  :hook (python-mode . (-juxt 'pyvenv-mode 'try/pyvenv-workon 'flycheck-mode 'company-mode 'yas-minor-mode)))
```

**Comment by hongyi-zhao** [comment]
> IMO `use-package` should be adapted to support your use-case, since it already tries to DWIM.

It has implemented the support of [using a list in car](https://github.com/jwiegley/use-package#hooks), but not cdr.
 
> The next best thing, IMO, is to write your own `use-package` keyword (see `use-package-keywords`) that does what you want. I don't use `use-package` anymore, but IIRC this was a supported use-case.

I still not so clear what's the corresponding code snippet for this method. Any more hints?

**Comment by hongyi-zhao** [comment]
> ```
> (-juxt 'pyvenv-mode 'try/pyvenv-workon 'flycheck-mode 'company-mode 'yas-minor-mode))
> ```

I want to have a function it can do something like the following:

(-juxt 'pyvenv-mode '(try/pyvenv-workon flycheck-mode company-mode yas-minor-mode))

or

(-juxt pyvenv-mode (try/pyvenv-workon flycheck-mode company-mode yas-minor-mode))

 
> `-juxt` will create a function that will call the functions in the list.

**Comment by hongyi-zhao** [comment]
>  If you place point after the `use-package` form and type `M-x pp-macroexpand-last-sexp RET` you can inspect what `use-package` is actually doing.

```emacs-lisp
(use-package python-mode
  :hook (python-mode . (-juxt 'pyvenv-mode 'try/pyvenv-workon 'flycheck-mode 'company-mode 'yas-minor-mode)))| 
```
`|` denotes the point position. `M-x pp-macroexpand-last-sexp RET` gives the following:
```emacs-lisp
(progn
  (straight-use-package 'python-mode)
  (defvar use-package--warning92
    #'(lambda
	(keyword err)
	(let
	    ((msg
	      (format "%s/%s: %s" 'python-mode keyword
		      (error-message-string err))))
	  (display-warning 'use-package msg :error))))
  (condition-case-unless-debug err
      (progn
	(unless
	    (fboundp 'python-mode)
	  (autoload #'python-mode "python-mode" nil t))
	(add-hook 'python-mode-hook #'python-mode)
	(add-hook '-juxt-hook #'python-mode)
	(add-hook 'quote-hook #'python-mode)
	(add-hook 'pyvenv-mode-hook #'python-mode)
	(add-hook 'quote-hook #'python-mode)
	(add-hook 'try/pyvenv-workon-hook #'python-mode)
	(add-hook 'quote-hook #'python-mode)
	(add-hook 'flycheck-mode-hook #'python-mode)
	(add-hook 'quote-hook #'python-mode)
	(add-hook 'company-mode-hook #'python-mode)
	(add-hook 'quote-hook #'python-mode)
	(add-hook 'yas-minor-mode-hook #'python-mode))
    (error
     (funcall use-package--warning92 :catch err))))
```


> Sorry, I don't understand what you mean, or how that is different to a flat list of `-juxt` arguments.

I just mean that let it supports the more concise forms without using the quoting symbols.

**Comment by basil-conto** [comment]
> `M-x pp-macroexpand-last-sexp RET` gives the following:

I know, I suggested using that command for your own benefit as you experiment with `use-package`.

> I mean, let it support a more concise form without using quoting (`'`) symbols.

You're always going to have at least one quote unless you call a macro.

**Comment by hongyi-zhao** [comment]
> You're always going to have at least one quote unless you call a macro.

Do you mean use a `defmacro` to do the job, and then eval/call the macro?

**Comment by basil-conto** [comment]
> > You're always going to have at least one quote unless you call a macro.
> 
> Do you mean use a `defmacro` to do the job, and then eval/call the macro?

I meant that, as long as you use higher-order functions (i.e. functions that accept other functions as arguments) on named functions (i.e. function symbols like `python-mode` rather than anonymous `lambda` functions), then you will always need to quote something, because function names are symbols (e.g. `#'python-mode`), not variables (e.g. `python-mode`).  Even a list of function symbols (e.g. `'(python-mode)`) needs to be quoted against evaluation.

The only way to refer to named functions as if they were variables is to use some sort of macro, because macro arguments are unevaluated forms.

Personally, I would rather write `(-juxt #'foo #'bar #'baz)` than `(some-cool-macro foo bar baz)`.  In the first case there are no surprises and the intent is clear: `-juxt` is a function that will evaluate all its arguments just once, and the arguments are function symbols.  In the second case the symbols could be anything, and it is not immediately clear what `some-cool-macro` does with those symbols.  The general convention is to always prefer functions over macros except when macros provide a very clear advantage in syntax and convenience.  I don't think this is one of those cases, but beauty lies in the eye of the beholder ;).
