### ISSUE TITLE
other types of sequences

### ISSUE THREAD

**Issue by gtusr** [magnars/dash.el#412]
What is the best advice for using these functions on other types of sequences, i.e. arrays?

Just use seq.el?  

Performance looks roughly comparable uncompiled:

[Performance comparison between seq.el, dash.el, and cl-lib.el](https://kisaragi-hiu.com/performance-cl-lib-dash-seq/)

**Comment by basil-conto** [comment]
> What is the best advice for using these functions

Which functions?

> on other types of sequences, i.e. arrays?

Just to clarify, `dash` does not support arrays.

> Just use seq.el?

In general that will depend on the particular use-case, what metric you're trying to optimise, personal preference, Emacs version, etc. so it's hard-to-impossible to give a one-size-fits-all answer.

Both `cl-lib` and `seq` are bundled with Emacs, so pick whichever suits your particular needs and tastes the best, or mix-and-match functions from both libraries as desired.

If I was forced to pick one and only one, I'd say `seq` because it offers maximal genericity, and can in many cases be improved (even by the user at runtime).

> Performance looks roughly comparable uncompiled:

Why are you interested in uncompiled performance?
Put differently, under which use-case does the performance of uncompiled Elisp matter?

> [Performance comparison between seq.el, dash.el, and cl-lib.el](https://kisaragi-hiu.com/performance-cl-lib-dash-seq/)

As with any collection of micro-benchmarks, take the conclusions of this post with several grains of salt:
- none of these comparisons involve arrays
- each library has different defaults and calling conventions for comparison predicates, which are not accounted for (e.g. `cl-lib` defaults to `eql` while the others default to `equal`)
- each library has different happy paths and pathological inputs, which is not accounted for (e.g. `cl-remove-duplicates` is time+space efficient on lists exclusively comprising duplicates, but is slow otherwise, whereas `-distinct` is the opposite)
- I'm not sure whether Emacs' eager macroexpansion is accounted for (code loaded from a `.el` library is macroexpanded once at load-time, whereas manually invoking e.g. `--filter` may incur the macroexpansion cost each time, and macroexpansion is comparatively very slow)

**Comment by gtusr** [comment]
Thanks for the detailed response.  I agree that benchmarks on uncompiled code are not all that useful and it's not clear why the author chose to publish them.  

Since the seq.el and cl-lib.el functions work on more the more general 'sequence' datatype in elisp, I'm left wondering about your motivation for creating the dash.el project ... and what it makes it so popular.

**Comment by basil-conto** [comment]
> I'm left wondering about your motivation for creating the dash.el project

Only @magnars can answer that.

My impression is that, when `dash` first began, the Emacs standard library was much poorer than it is today, and the better namespaced `cl-lib` had not yet (or had just recently) been refactored from the older and discouraged/deprecated `cl` package.

> and what it makes it so popular.

Further to the point above, I imagine a major contributing factor was the extensive and terse API which catered to lots of different tastes: anaphoric, destructuring, Clojure-inspired `*-let` and threading macros, and higher-order function combinators for a functional programming style, and all of these before any kind of equally convenient alternative was widely available in vanilla Emacs.

I speculate that the appearance of `dash` around 2012, coinciding with rapidly growing interest in third-party Elisp packages and archives, was not a coincidence, and neither was its subsequent popularity: just its historic use by popular packages like Magit and `lsp-mode` alone would be enough to give it some critical mass.

See also:
- #43
- #179

**Comment by gtusr** [comment]
> Further to the point above, I imagine a major contributing factor was the extensive and terse API which catered to lots of different tastes: anaphoric, destructuring, Clojure-inspired *-let and threading macros, and higher-order function combinators for a functional programming style, and all of these before any kind of equally convenient alternative was widely available in vanilla Emacs.

I come from a background having used Mathematica in industry for many years through its often highly frustrating Notebook interface.  The Wolfram language has a very nice API though for the same type of functionality that dash.el provides, which is why dash caught my attention as I am starting to use emacs + org-mode + babel + latex for more of my own work.  

The pointers to those discussions on the earlier development of dash were also quite illuminating.  Thanks.
